Make types/rbush a dependency (#184)
The types exposed by protomaps-leaflet
import rbush, which causes an error
for projects that have no direct
dependency on types/rbush:

node_modules/protomaps-leaflet/dist/esm/index.d.ts:3:19 - error TS7016: Could not find a declaration file for module 'rbush'. '/files/node_modules/rbush/rbush.js' implicitly has an 'any' type.

Make types/rbush a dependency instead,
similar to how commit ca5ba0ab did
it for types/css-font-loading-module.